name: "Convert TODOs to Issues"
on:
  push:
    branches: [main]
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "TODOs to Issues"
              uses: "alstr/todo-to-issue-action@v4"